include:
  - project: 'IsyFact/isy-gitlabci-templates'
    file: '/maven/.gitlab-ci-maven.yml'

variables:
  NEXT_VERSION: 6.0.0

build:
  extends: .maven-build

test:
  extends: .maven-test

package:
  extends: .maven-package

#deploy:
#  extends: .maven-deploy

stages:
  - build
  - test
  - package
#  - deploy
