name: Release Maven
on:
  release:
    types: [released]

jobs:
  Build:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_build_template.yml@v1.6.0
    with:
      version: ${{ github.ref_name }}
      sonar-skip: true

  DeployReleaseVersion:
    needs: [Build]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v1.6.0
    with:
      version: ${{ github.ref_name }}
      maven-opts: '-P webguiRelease'
      deploy-server-id: central
      sbom: true
      sign: true
      environment: 'Release'
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
