name: Maven Build
on:
  pull_request:
    branches:
      - release/5.x
  push:
    branches:
      - release/5.x

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn $MAVEN_CLI_OPTS -Dcheckstyle.skip compile

  CodeQuality:
    runs-on: ubuntu-latest
    needs: [Compile]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Checkstyle
        run: mvn $MAVEN_CLI_OPTS compile checkstyle:checkstyle-aggregate
      - name: Spotbugs
        run: mvn $MAVEN_CLI_OPTS -Dcheckstyle.skip -Denforcer.skip -Dtidy.skip compile spotbugs:check